MESSAGE(STATUS "********* Conan FindMySQL wrapper! **********")

find_path(MYSQL_INCLUDE_DIR mysql.h ${CONAN_INCLUDE_DIRS_MYSQLCLIENT})
find_library(MYSQL_LIBRARY NAMES ${CONAN_LIBS_MYSQLCLIENT} PATHS ${CONAN_LIB_DIRS_MYSQLCLIENT})

MESSAGE("** MYSQL ALREADY FOUND BY CONAN!")
SET(MYSQL_FOUND TRUE)
MESSAGE("** FOUND MYSQL:  ${MYSQL_LIBRARY}")
MESSAGE("** FOUND MYSQL INCLUDE:  ${MYSQL_INCLUDE_DIR}")

set(MYSQL_INCLUDE_DIRS ${MYSQL_INCLUDE_DIR})
set(MYSQL_LIBRARIES ${MYSQL_LIBRARY})

mark_as_advanced(ZLIB_LIBRARY ZLIB_INCLUDE_DIR)